apiVersion: v1
kind: Pod
metadata:
  name: web-login-site.example.com
  labels:
    app: web-login-site
spec:
  containers:
  - name: web-login-site-1
    image: cybersmithio/web-login-site
    ports:
    - name: webloginport
      containerPort: 443